<?php

/**
 * @file
 * Taxonomy fields formatter module main file.
 */

/**
 * Implements hook_field_formatter_info().
 */
function taxonomy_field_formatter_field_formatter_info() {
  return array(
    'taxonomy_term_entity' => array(
      'label' => t('Rendered entity'),
      'field types' => array('taxonomy_term_reference'),
      'settings' => array('view_mode' => 'default'),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function taxonomy_field_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $settings = $instance['display'][$view_mode]['settings'];
  $default_view_mode = $settings['view_mode'];

  $entity_info = entity_get_info('taxonomy_term');
  $options = array('default' => t("Default"));
  foreach ($entity_info['view modes'] as $term_view_mode => $data) {
    $options[$term_view_mode] = $data['label'];
  }
  $element['view_mode'] = array(
    '#title' => t('Display mode'),
    '#description' => t('The display mode in which to render the taxonomy term'),
    '#type' => 'select',
    '#default_value' => isset($settings['view_mode']) ? $settings['view_mode'] : $default_view_mode,
    '#options' => $options,
  );
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function taxonomy_field_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $settings = $instance['display'][$view_mode]['settings'];
  $entity_info = entity_get_info('taxonomy_term');

  $summary = array();

  if ($settings['view_mode'] == 'default') {
    $view_mode_label = t("Default");
  }
  elseif (!empty($entity_info['view modes'][$settings['view_mode']]['label'])) {
    $view_mode_label = $entity_info['view modes'][$settings['view_mode']]['label'];
  }
  else {
    $view_mode_label = $settings['view_mode'];
  }
  $summary[] = t("Display mode: @view_mode", array('@view_mode' => $view_mode_label));

  return implode('<br>', $summary);
}

/**
 * Implements hook_field_formatter_view().
 * @see taxonomy_field_formatter_field_formatter_info()
 */
function taxonomy_field_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  if ($display['type'] == 'taxonomy_term_entity') {
    foreach ($items as $delta => $item) {
      if ($term = taxonomy_term_load($item['tid'])) {
        $element[$delta] = taxonomy_term_view($term, $display['settings']['view_mode']);
      }
    }
  }
  return $element;
}
